name: tiktok_mobile_sdk
description: "TikTok OpenSDK."
version: 0.0.3
homepage:

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.artarch.tiktok_mobile_sdk
        pluginClass: TiktokMobileSdkPlugin
      ios:
        pluginClass: TiktokMobileSdkPlugin